package dough

// Currency - struct containing currency variables
type Currency struct {
	Unit                string
	Alpha               string
	Numeric             string
	Symbol              string
	Fraction            int
	Decimal             string
	Grouping            int
	Delimiter           string
	SymbolPositionFront bool
}

// CurrencyList - complete list of supported currencies
var CurrencyList = map[string]Currency{
	"AED": {
		Unit:                "UAE Dirham",
		Alpha:               "AED",
		Numeric:             "784",
		Symbol:              "\u0625\u002E\u062F",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: false,
	},
	"AFN": {
		Unit:                "Afghani",
		Alpha:               "AFN",
		Numeric:             "971",
		Symbol:              "\u060B",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"ALL": {
		Unit:                "Lek",
		Alpha:               "ALL",
		Numeric:             "008",
		Symbol:              "\u004c\u0065\u006B",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"AMD": {
		Unit:                "Armenian Dram",
		Alpha:               "AMD",
		Numeric:             "051",
		Symbol:              "\u058F",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"ANG": {
		Unit:                "Netherlands Antillean Guilder",
		Alpha:               "ANG",
		Numeric:             "532",
		Symbol:              "\u0192",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"AOA": {
		Unit:                "Kwanza",
		Alpha:               "AOA",
		Numeric:             "973",
		Symbol:              "\u004B\u007A",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"ARS": {
		Unit:                "Argentine Peso",
		Alpha:               "ARS",
		Numeric:             "032",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ",",
		Grouping:            3,
		Delimiter:           ".",
		SymbolPositionFront: true,
	},
	"AUD": {
		Unit:                "Australian Dollar",
		Alpha:               "AUD",
		Numeric:             "036",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           " ",
		SymbolPositionFront: true,
	},
	"AWG": {
		Unit:                "Aruban Florin",
		Alpha:               "AWG",
		Numeric:             "533",
		Symbol:              "\u0192",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"AZN": {
		Unit:                "Azerbaijan Manat",
		Alpha:               "AZN",
		Numeric:             "944",
		Symbol:              "\u20BC",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"BAM": {
		Unit:                "Convertible Mark",
		Alpha:               "BAM",
		Numeric:             "977",
		Symbol:              "\u004B\u004D",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"BBD": {
		Unit:                "Barbados Dollar",
		Alpha:               "BBD",
		Numeric:             "052",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"BDT": {
		Unit:                "Taka",
		Alpha:               "BDT",
		Numeric:             "050",
		Symbol:              "\u0054\u006B",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"BGN": {
		Unit:                "Bulgarian Lev",
		Alpha:               "BGN",
		Numeric:             "975",
		Symbol:              "\u043B\u0432",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"BHD": {
		Unit:                "Bahraini Dinar",
		Alpha:               "BHD",
		Numeric:             "048",
		Symbol:              "\u002e\u062f\u002e\u0628",
		Fraction:            3,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"BIF": {
		Unit:                "Burundi Franc",
		Alpha:               "BIF",
		Numeric:             "108",
		Symbol:              "\u0046\u0042\u0075",
		Fraction:            0,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"BMD": {
		Unit:                "Bermudian Dollar",
		Alpha:               "BMD",
		Numeric:             "060",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"BND": {
		Unit:                "Brunei Dollar",
		Alpha:               "BND",
		Numeric:             "096",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"BOB": {
		Unit:                "Boliviano",
		Alpha:               "BOB",
		Numeric:             "068",
		Symbol:              "\u0024\u0062",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"BRL": {
		Unit:                "Brazilian Real",
		Alpha:               "BRL",
		Numeric:             "986",
		Symbol:              "\u0052\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"BSD": {
		Unit:                "Bahamian Dollar",
		Alpha:               "BSD",
		Numeric:             "044",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"BTN": {
		Unit:                "Ngultrum",
		Alpha:               "BTN",
		Numeric:             "064",
		Symbol:              "\u004e\u0075\u002e",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"BWP": {
		Unit:                "Pula",
		Alpha:               "BWP",
		Numeric:             "072",
		Symbol:              "\u0050",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"BYN": {
		Unit:                "Belarusian Ruble",
		Alpha:               "BYN",
		Numeric:             "933",
		Symbol:              "\u0042\u0072",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"BZD": {
		Unit:                "Belize Dollar",
		Alpha:               "BZD",
		Numeric:             "084",
		Symbol:              "\u0042\u005a\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"CAD": {
		Unit:                "Canadian Dollar",
		Alpha:               "CAD",
		Numeric:             "124",
		Symbol:              "\u0043\u0041\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"CDF": {
		Unit:                "Congolese Franc",
		Alpha:               "CDF",
		Numeric:             "976",
		Symbol:              "\u0046\u0043",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"CHF": {
		Unit:                "Swiss Franc",
		Alpha:               "CHF",
		Numeric:             "756",
		Symbol:              "\u0043\u0048\u0046",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"CLP": {
		Unit:                "Chilean Peso",
		Alpha:               "CLP",
		Numeric:             "152",
		Symbol:              "\u0024",
		Fraction:            0,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"CNY": {
		Unit:                "Yuan Renminbi",
		Alpha:               "CNY",
		Numeric:             "156",
		Symbol:              "\u00a5",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"COP": {
		Unit:                "Colombian Peso",
		Alpha:               "COP",
		Numeric:             "170",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"CRC": {
		Unit:                "Costa Rican Colon",
		Alpha:               "CRC",
		Numeric:             "188",
		Symbol:              "\u20a1",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"CUC": {
		Unit:                "Peso Convertible",
		Alpha:               "CUC",
		Numeric:             "931",
		Symbol:              "\u0043\u0055\u0043\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"CUP": {
		Unit:                "Cuban Peso",
		Alpha:               "CUP",
		Numeric:             "192",
		Symbol:              "\u20b1",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"CVE": {
		Unit:                "Cabo Verde Escudo",
		Alpha:               "CVE",
		Numeric:             "132",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"CZK": {
		Unit:                "Czech Koruna",
		Alpha:               "CZK",
		Numeric:             "203",
		Symbol:              "\u004b\u010d",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"DJF": {
		Unit:                "Djibouti Franc",
		Alpha:               "DJF",
		Numeric:             "262",
		Symbol:              "\u0046\u0064\u006a",
		Fraction:            0,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"DKK": {
		Unit:                "Danish Krone",
		Alpha:               "DKK",
		Numeric:             "208",
		Symbol:              "\u006b\u0072\u002e",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"DOP": {
		Unit:                "Dominican Peso",
		Alpha:               "DOP",
		Numeric:             "214",
		Symbol:              "\u0052\u0044\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"DZD": {
		Unit:                "Algerian Dinar",
		Alpha:               "DZD",
		Numeric:             "012",
		Symbol:              "\u0044\u0041",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"EGP": {
		Unit:                "Egyptian Pound",
		Alpha:               "EGP",
		Numeric:             "818",
		Symbol:              "\u00a3",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"ERN": {
		Unit:                "Nakfa",
		Alpha:               "ERN",
		Numeric:             "232",
		Symbol:              "\u004e\u006b\u0066",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"ETB": {
		Unit:                "Ethiopian Birr",
		Alpha:               "ETB",
		Numeric:             "230",
		Symbol:              "\u0042\u0072",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"EUR": {
		Unit:                "Euro",
		Alpha:               "EUR",
		Numeric:             "978",
		Symbol:              "\u20ac",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"FJD": {
		Unit:                "Fiji Dollar",
		Alpha:               "FJD",
		Numeric:             "242",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"FKP": {
		Unit:                "Falkland Islands Pound",
		Alpha:               "FKP",
		Numeric:             "238",
		Symbol:              "\u00a3",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"GBP": {
		Unit:                "Pound Sterling",
		Alpha:               "GBP",
		Numeric:             "826",
		Symbol:              "\u00a3",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"GEL": {
		Unit:                "Lari",
		Alpha:               "GEL",
		Numeric:             "981",
		Symbol:              "\u20be",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"GHS": {
		Unit:                "Ghana Cedi",
		Alpha:               "GHS",
		Numeric:             "936",
		Symbol:              "\u0047\u0048\u00a2",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"GIP": {
		Unit:                "Gibraltar Pound",
		Alpha:               "GIP",
		Numeric:             "292",
		Symbol:              "\u00a3",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"GMD": {
		Unit:                "Dalasi",
		Alpha:               "GMD",
		Numeric:             "270",
		Symbol:              "\u0044",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"GNF": {
		Unit:                "Guinean Franc",
		Alpha:               "GNF",
		Numeric:             "324",
		Symbol:              "\u0046\u0047",
		Fraction:            0,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"GTQ": {
		Unit:                "Quetzal",
		Alpha:               "GTQ",
		Numeric:             "320",
		Symbol:              "\u0051",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"GYD": {
		Unit:                "Guyana Dollar",
		Alpha:               "GYD",
		Numeric:             "328",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"HKD": {
		Unit:                "Hong Kong Dollar",
		Alpha:               "HKD",
		Numeric:             "344",
		Symbol:              "\u0048\u004b\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"HNL": {
		Unit:                "Lempira",
		Alpha:               "HNL",
		Numeric:             "340",
		Symbol:              "\u004c",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"HRK": {
		Unit:                "Kuna",
		Alpha:               "HRK",
		Numeric:             "191",
		Symbol:              "\u006b\u006e",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"HTG": {
		Unit:                "Gourde",
		Alpha:               "HTG",
		Numeric:             "332",
		Symbol:              "\u0047",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"HUF": {
		Unit:                "Forint",
		Alpha:               "HUF",
		Numeric:             "348",
		Symbol:              "\u0046\u0074",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"IDR": {
		Unit:                "Rupiah",
		Alpha:               "IDR",
		Numeric:             "360",
		Symbol:              "\u0052\u0070",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"ILS": {
		Unit:                "New Israeli Sheqel",
		Alpha:               "ILS",
		Numeric:             "376",
		Symbol:              "\u20aa",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"INR": {
		Unit:                "Indian Rupee",
		Alpha:               "INR",
		Numeric:             "356",
		Symbol:              "\u20b9",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"IQD": {
		Unit:                "Iraqi Dinar",
		Alpha:               "IQD",
		Numeric:             "368",
		Symbol:              "\u0639\u002e\u062f",
		Fraction:            3,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"IRR": {
		Unit:                "Iranian Rial",
		Alpha:               "IRR",
		Numeric:             "364",
		Symbol:              "\ufdfc",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"ISK": {
		Unit:                "Iceland Krona",
		Alpha:               "ISK",
		Numeric:             "352",
		Symbol:              "\u006b\u0072",
		Fraction:            0,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"JMD": {
		Unit:                "Jamaican Dollar",
		Alpha:               "JMD",
		Numeric:             "388",
		Symbol:              "\u004a\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"JOD": {
		Unit:                "Jordanian Dinar",
		Alpha:               "JOD",
		Numeric:             "400",
		Symbol:              "\u062f\u002e\u0627",
		Fraction:            3,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"JPY": {
		Unit:                "Yen",
		Alpha:               "JPY",
		Numeric:             "392",
		Symbol:              "\u00a5",
		Fraction:            0,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"KES": {
		Unit:                "Kenyan Shilling",
		Alpha:               "KES",
		Numeric:             "404",
		Symbol:              "\u004b\u0053\u0068",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"KGS": {
		Unit:                "Som",
		Alpha:               "KGS",
		Numeric:             "417",
		Symbol:              "\u043b\u0432",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"KHR": {
		Unit:                "Riel",
		Alpha:               "KHR",
		Numeric:             "116",
		Symbol:              "\u17db",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"KMF": {
		Unit:                "Comorian Franc ",
		Alpha:               "KMF",
		Numeric:             "174",
		Symbol:              "\u0043\u0046",
		Fraction:            0,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"KPW": {
		Unit:                "North Korean Won",
		Alpha:               "KPW",
		Numeric:             "408",
		Symbol:              "\u20a9",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"KRW": {
		Unit:                "Won",
		Alpha:               "KRW",
		Numeric:             "410",
		Symbol:              "\u20a9",
		Fraction:            0,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"KWD": {
		Unit:                "Kuwaiti Dinar",
		Alpha:               "KWD",
		Numeric:             "414",
		Symbol:              "\u0643",
		Fraction:            3,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"KYD": {
		Unit:                "Cayman Islands Dollar",
		Alpha:               "KYD",
		Numeric:             "136",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"KZT": {
		Unit:                "Tenge",
		Alpha:               "KZT",
		Numeric:             "398",
		Symbol:              "\u20b8",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"LAK": {
		Unit:                "Lao Kip",
		Alpha:               "LAK",
		Numeric:             "418",
		Symbol:              "\u20ad",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"LBP": {
		Unit:                "Lebanese Pound",
		Alpha:               "LBP",
		Numeric:             "422",
		Symbol:              "\u002e\u0644\u002e\u0644",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"LKR": {
		Unit:                "Sri Lanka Rupee",
		Alpha:               "LKR",
		Numeric:             "144",
		Symbol:              "\u20a8",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"LRD": {
		Unit:                "Liberian Dollar",
		Alpha:               "LRD",
		Numeric:             "430",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"LSL": {
		Unit:                "Loti",
		Alpha:               "LSL",
		Numeric:             "426",
		Symbol:              "\u004c",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"LYD": {
		Unit:                "Libyan Dinar",
		Alpha:               "LYD",
		Numeric:             "434",
		Symbol:              "\u004c\u0044",
		Fraction:            3,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"MAD": {
		Unit:                "Moroccan Dirham",
		Alpha:               "MAD",
		Numeric:             "504",
		Symbol:              "\u0044\u0048",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"MDL": {
		Unit:                "Moldovan Leu",
		Alpha:               "MDL",
		Numeric:             "498",
		Symbol:              "\u004d\u0044\u004c",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"MGA": {
		Unit:                "Malagasy Ariary",
		Alpha:               "MGA",
		Numeric:             "969",
		Symbol:              "\u0041\u0072",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"MKD": {
		Unit:                "Denar",
		Alpha:               "MKD",
		Numeric:             "807",
		Symbol:              "\u0434\u0435\u043d",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"MMK": {
		Unit:                "Kyat",
		Alpha:               "MMK",
		Numeric:             "104",
		Symbol:              "\u004b",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"MNT": {
		Unit:                "Tugrik",
		Alpha:               "MNT",
		Numeric:             "496",
		Symbol:              "\u20ae",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"MOP": {
		Unit:                "Pataca",
		Alpha:               "MOP",
		Numeric:             "446",
		Symbol:              "\u004d\u004f\u0050\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"MRU": {
		Unit:                "Ouguiya",
		Alpha:               "MRU",
		Numeric:             "929",
		Symbol:              "\u0055\u004d",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"MUR": {
		Unit:                "Mauritius Rupee",
		Alpha:               "MUR",
		Numeric:             "480",
		Symbol:              "\u20a8",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"MVR": {
		Unit:                "Rufiyaa",
		Alpha:               "MVR",
		Numeric:             "462",
		Symbol:              "\u0052\u0066",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"MWK": {
		Unit:                "Malawi Kwacha",
		Alpha:               "MWK",
		Numeric:             "454",
		Symbol:              "\u004d\u004b",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"MXN": {
		Unit:                "Mexican Peso",
		Alpha:               "MXN",
		Numeric:             "484",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"MYR": {
		Unit:                "Malaysian Ringgit",
		Alpha:               "MYR",
		Numeric:             "458",
		Symbol:              "\u0052\u004d",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"MZN": {
		Unit:                "Mozambique Metical",
		Alpha:               "MZN",
		Numeric:             "943",
		Symbol:              "\u004d\u0054",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"NAD": {
		Unit:                "Namibia Dollar",
		Alpha:               "NAD",
		Numeric:             "516",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"NGN": {
		Unit:                "Naira",
		Alpha:               "NGN",
		Numeric:             "566",
		Symbol:              "\u20a6",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"NIO": {
		Unit:                "Cordoba Oro",
		Alpha:               "NIO",
		Numeric:             "558",
		Symbol:              "\u0043\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"NOK": {
		Unit:                "Norwegian Krone",
		Alpha:               "NOK",
		Numeric:             "578",
		Symbol:              "\u006b\u0072",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"NPR": {
		Unit:                "Nepalese Rupee",
		Alpha:               "NPR",
		Numeric:             "524",
		Symbol:              "\u20a8",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"NZD": {
		Unit:                "New Zealand Dollar",
		Alpha:               "NZD",
		Numeric:             "554",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"OMR": {
		Unit:                "Rial Omani",
		Alpha:               "OMR",
		Numeric:             "512",
		Symbol:              "\ufdfc",
		Fraction:            3,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"PAB": {
		Unit:                "Balboa",
		Alpha:               "PAB",
		Numeric:             "590",
		Symbol:              "\u0042\u002f\u002e",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"PEN": {
		Unit:                "Sol",
		Alpha:               "PEN",
		Numeric:             "604",
		Symbol:              "\u0053\u002f\u002e",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"PGK": {
		Unit:                "Kina",
		Alpha:               "PGK",
		Numeric:             "598",
		Symbol:              "\u004b",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"PHP": {
		Unit:                "Philippine Peso",
		Alpha:               "PHP",
		Numeric:             "608",
		Symbol:              "\u20b1",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"PKR": {
		Unit:                "Pakistan Rupee",
		Alpha:               "PKR",
		Numeric:             "586",
		Symbol:              "\u20a8",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"PLN": {
		Unit:                "Zloty",
		Alpha:               "PLN",
		Numeric:             "985",
		Symbol:              "\u007a\u0142",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"PYG": {
		Unit:                "Guarani",
		Alpha:               "PYG",
		Numeric:             "600",
		Symbol:              "\u0047\u0073",
		Fraction:            0,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"QAR": {
		Unit:                "Qatari Rial",
		Alpha:               "QAR",
		Numeric:             "634",
		Symbol:              "\ufdfc",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"RON": {
		Unit:                "Romanian Leu",
		Alpha:               "RON",
		Numeric:             "946",
		Symbol:              "\u006c\u0065\u0069",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"RSD": {
		Unit:                "Serbian Dinar",
		Alpha:               "RSD",
		Numeric:             "941",
		Symbol:              "\u0420\u0421\u0414",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"RUB": {
		Unit:                "Russian Ruble",
		Alpha:               "RUB",
		Numeric:             "643",
		Symbol:              "\u20bd",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"RWF": {
		Unit:                "Rwanda Franc",
		Alpha:               "RWF",
		Numeric:             "646",
		Symbol:              "\u0046\u0052\u0077",
		Fraction:            0,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"SAR": {
		Unit:                "Saudi Riyal",
		Alpha:               "SAR",
		Numeric:             "682",
		Symbol:              "\ufdfc",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"SBD": {
		Unit:                "Solomon Islands Dollar",
		Alpha:               "SBD",
		Numeric:             "090",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"SCR": {
		Unit:                "Seychelles Rupee",
		Alpha:               "SCR",
		Numeric:             "690",
		Symbol:              "\u20a8",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"SDG": {
		Unit:                "Sudanese Pound",
		Alpha:               "SDG",
		Numeric:             "938",
		Symbol:              "\u062c\u002e\u0633\u002e",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"SEK": {
		Unit:                "Swedish Krona",
		Alpha:               "SEK",
		Numeric:             "752",
		Symbol:              "\u006b\u0072",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"SGD": {
		Unit:                "Singapore Dollar",
		Alpha:               "SGD",
		Numeric:             "702",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"SHP": {
		Unit:                "Saint Helena Pound",
		Alpha:               "SHP",
		Numeric:             "654",
		Symbol:              "\u00a3",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"SLL": {
		Unit:                "Leone",
		Alpha:               "SLL",
		Numeric:             "694",
		Symbol:              "\u004c\u0065",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"SOS": {
		Unit:                "Somali Shilling",
		Alpha:               "SOS",
		Numeric:             "706",
		Symbol:              "\u0053",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"SRD": {
		Unit:                "Surinam Dollar",
		Alpha:               "SRD",
		Numeric:             "968",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"SSP": {
		Unit:                "South Sudanese Pound",
		Alpha:               "SSP",
		Numeric:             "728",
		Symbol:              "\u00a3",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"STN": {
		Unit:                "Dobra",
		Alpha:               "STN",
		Numeric:             "930",
		Symbol:              "\u0044\u0062",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"SVC": {
		Unit:                "El Salvador Colon",
		Alpha:               "SVC",
		Numeric:             "222",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"SYP": {
		Unit:                "Syrian Pound",
		Alpha:               "SYP",
		Numeric:             "760",
		Symbol:              "\u00a3",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"SZL": {
		Unit:                "Lilangeni",
		Alpha:               "SZL",
		Numeric:             "748",
		Symbol:              "\u004c",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"THB": {
		Unit:                "Baht",
		Alpha:               "THB",
		Numeric:             "764",
		Symbol:              "\u0e3f",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"TJS": {
		Unit:                "Somoni",
		Alpha:               "TJS",
		Numeric:             "972",
		Symbol:              "\u0405\u004d",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"TMT": {
		Unit:                "Turkmenistan New Manat",
		Alpha:               "TMT",
		Numeric:             "934",
		Symbol:              "\u0054",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"TND": {
		Unit:                "Tunisian Dinar",
		Alpha:               "TND",
		Numeric:             "788",
		Symbol:              "\u062f\u002e\u062a",
		Fraction:            3,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"TOP": {
		Unit:                "Pa’anga",
		Alpha:               "TOP",
		Numeric:             "776",
		Symbol:              "\u0054\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"TRY": {
		Unit:                "Turkish Lira",
		Alpha:               "TRY",
		Numeric:             "949",
		Symbol:              "\u20ba",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"TTD": {
		Unit:                "Trinidad and Tobago Dollar",
		Alpha:               "TTD",
		Numeric:             "780",
		Symbol:              "\u0054\u0054\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"TWD": {
		Unit:                "New Taiwan Dollar",
		Alpha:               "TWD",
		Numeric:             "901",
		Symbol:              "\u004e\u0054\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"TZS": {
		Unit:                "Tanzanian Shilling",
		Alpha:               "TZS",
		Numeric:             "834",
		Symbol:              "\u0054\u0053\u0068",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"UAH": {
		Unit:                "Hryvnia",
		Alpha:               "UAH",
		Numeric:             "980",
		Symbol:              "\u20b4",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"UGX": {
		Unit:                "Uganda Shilling",
		Alpha:               "UGX",
		Numeric:             "800",
		Symbol:              "\u0055\u0047\u0058",
		Fraction:            0,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"USD": {
		Unit:                "US Dollar",
		Alpha:               "USD",
		Numeric:             "840",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"UYU": {
		Unit:                "Peso Uruguayo",
		Alpha:               "UYU",
		Numeric:             "858",
		Symbol:              "\u0024\u0055",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"UZS": {
		Unit:                "Uzbekistan Sum",
		Alpha:               "UZS",
		Numeric:             "860",
		Symbol:              "\u043b\u0432",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"VES": {
		Unit:                "Bolívar Soberano",
		Alpha:               "VES",
		Numeric:             "928",
		Symbol:              "\u0042\u0073\u002e \u0053",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"VND": {
		Unit:                "Dong",
		Alpha:               "VND",
		Numeric:             "704",
		Symbol:              "\u20ab",
		Fraction:            0,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"VUV": {
		Unit:                "Vatu",
		Alpha:               "VUV",
		Numeric:             "548",
		Symbol:              "\u0056\u0054",
		Fraction:            0,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"WST": {
		Unit:                "Tala",
		Alpha:               "WST",
		Numeric:             "882",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"XAF": {
		Unit:                "CFA Franc BEAC",
		Alpha:               "XAF",
		Numeric:             "950",
		Symbol:              "\u0046\u0043\u0046\u0041",
		Fraction:            0,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"XCD": {
		Unit:                "East Caribbean Dollar",
		Alpha:               "XCD",
		Numeric:             "951",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"XOF": {
		Unit:                "CFA Franc BCEAO",
		Alpha:               "XOF",
		Numeric:             "952",
		Symbol:              "\u0043\u0046\u0041",
		Fraction:            0,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"XPF": {
		Unit:                "CFP Franc",
		Alpha:               "XPF",
		Numeric:             "953",
		Symbol:              "\u20a3",
		Fraction:            0,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"YER": {
		Unit:                "Yemeni Rial",
		Alpha:               "YER",
		Numeric:             "886",
		Symbol:              "\ufdfc",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"ZAR": {
		Unit:                "Rand",
		Alpha:               "ZAR",
		Numeric:             "710",
		Symbol:              "\u0052",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"ZMW": {
		Unit:                "Zambian Kwacha",
		Alpha:               "ZMW",
		Numeric:             "967",
		Symbol:              "\u005a\u004b",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
	"ZWL": {
		Unit:                "Zimbabwe Dollar",
		Alpha:               "ZWL",
		Numeric:             "932",
		Symbol:              "\u0024",
		Fraction:            2,
		Decimal:             ".",
		Grouping:            3,
		Delimiter:           ",",
		SymbolPositionFront: true,
	},
}
